import 'package:get/get.dart';

class MyLocale implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en": {
          "HOME": "HOME",
          "Purchases": "Purchases",
          "Make Sale": "Make Sale",
          "Vendor Master": "Vendor Master",
          "Stock Report": "Stock Report",
          "Accounts": "Accounts",
          "Performance": "Performance",
          "Generate Offers": "Generate Offers",
          "Reset Maneger Password": "Reset Maneger Password",
          "Reset Password": "Reset Password",
          "Logout": "Logout",
          "Cancel": "Cancel",
          "Yes": "Yes",
          "Product Name": "Product Name",
          "Cost": "Cost",
          "Price": "Price",
          "Quantity": "Quantity",
          "Available Quantity": "Available Quantity",
          "Total": "Total",
          "TOTAL": "TOTAL",
          "Sold Quantity": "Sold Quantity",
          "Search Product Name Or SN": "Search Product Name Or SN",
          "Choose Bill Date": "Choose Bill Date",
          "Make A Sale": "Make A Sale",
          "Buy from a Supplier": "Buy from a Supplier",
          "Payment": "Payment",
          "BUY": "BUY",
          "Cashier Screens": "Cashier Screens",
          "Add New Supplier": "Add New Supplier",
          "Supplier Name": "Supplier Name",
          "Save": "Save",
          "Phone number": "Phone number",
          "Suppliers List": "Suppliers List",
          "Category": "Category",
          "Products List": "Products List",
          "Delete": "Delete",
          "Edit": "Edit",
          "Login": "Login",
          "Name": "Name",
          "Email": "Email",
          "Sign Up": "Sign Up",
          "Password": "Password",
          "The e-mail not valid": "The e-mail not valid",
          "The field is empty": "The field is empty",
          "Don't Have An Account?": "Don't Have An Account?",
          "Already Have A Account?": "Already Have A Account?",
          "Maneger Password": "Maneger Password",
          "Maneger": "Maneger",
          "Employees": "Employees",
          "Changing": "Changing",
          "The password is less than 8 char": "The password is less than 8 char",
          "Sales": "Sales",
          "Seles Reports": "Sales Reports",
          "New Password": "New Password",
          "Current Password": "Current Password",
          "Product Information": "Product Information",
          "New Quantity": "New Quantity",
          "Old cost": "Old cost",
          "New cost": "New cost",
          "Done": "Done",
          "Success process": "Success process",
          "Alert!": "Alert!",
          "Change Language": "Change Language",
          "Stock In QTY": "Stock In QTY",
          "Rate per QTY": "Rate per QTY",
          "Total Value": "Total Value",
          "Category Master": "Category Master",
          "Sub Category Master": "Sub Category Master",
          "Item Master": "Item Master",
          "Brand Master": "Brand Master",
          "Company Profile": "Company Profile",
          "Business Details": "Business Details",
          "Business Name": "Business Name",
          "Contact Details": "Contact Details",
          "Contact Person Name": "Contact Person Name",
          "Contact Number": "Contact Number",
          "Email ID": "Email ID",
          "Business Number": "Business Number",
          "PAN": "PAN",
          "GST": "GST",
          "Registration Number": "Registration Number",
          "Licence Number": "Licence Number",
          "Business Description": "Business Description",
          "Social Media": "Social Media",
          "Website": "Website",
          "LinkedIn": "LinkedIn",
          "Instagram": "Instagram",
          "Facebook": "Facebook",
          "X": "X",
          "Miscellaneous Info": "Miscellaneous Info",
          "Active": "Active",
          "Inactive": "Inactive",
          "Order Type": "Order Type",
          "Item wise": "Item wise",
          "Combo": "Combo",
          "Discount": "Discount",
          "Net Payable Amount": "Net Payable Amount",
          "Make Purchase": "Make Purchase",
          "Vendor": "Vendor",
          "Purchase Reports": "Purchase Reports",
          "Masters Setup": "Masters Setup",
          "Address": "Address",
          "City": "City",
          "Pin Code": "Pin Code",
          "State": "State",
          "Country": "Country",
          "Logo": "Logo",
          "Profile Photo": "Profile Photo",
          "Success": "Success",
          "Company profile saved!": "Company profile saved!",
          "Tap to upload logo": "Tap to upload logo",
          "Logo Uploaded": "Logo Uploaded",
          "Profile Photo Uploaded": "Profile Photo Uploaded",
          "Welcome Back": "Welcome Back",
          "Sign in to your store account": "Sign in to your store account",
          "Create Account": "Create Account",
          "Set up your store account": "Set up your store account",
          "Continue with Google": "Continue with Google",
          "Select Language": "Select Language",
          "Full Name": "Full Name",
          "The field is empty": "The field is empty",
          "Password must be at least 8 characters": "Password must be at least 8 characters",
          "Sign In Failed": "Sign In Failed",
          "OR": "OR",
          "Already have an account?": "Already have an account?",
          "Required": "Required",
          "Category Name": "Category Name",
          "Sub Category Name": "Sub Category Name",
          "Brand Name": "Brand Name",
          "Item Name": "Item Name",
          "Status": "Status",
          "Sub Categories": "Sub Categories",
          "Category Details": "Category Details",
          "Sub Category Details": "Sub Category Details",
          "Brand Details": "Brand Details",
          "Item Details": "Item Details",
          "Back": "Back",
          "Add Category": "Add Category",
          "Edit Category": "Edit Category",
          "Add Sub Category": "Add Sub Category",
          "Edit Sub Category": "Edit Sub Category",
          "Add Brand": "Add Brand",
          "Edit Brand": "Edit Brand",
          "Add Item": "Add Item",
          "Edit Item": "Edit Item",
          "Combo Price": "Combo Price",
          "Items in Combo": "Items in Combo",
          "QTY": "QTY",
          "Add Combo": "Add Combo",
          "Edit Combo": "Edit Combo",
          "No combos yet. Tap + to add.": "No combos yet. Tap + to add.",
          "Add at least one item": "Add at least one item",
          "No vendors yet. Tap + to add.": "No vendors yet. Tap + to add.",
          "Add Vendor": "Add Vendor",
          "Edit Vendor": "Edit Vendor",
          "Seles Reports": "Sales Reports",
          "Add User": "Add User",
          "Add New User": "Add New User",
          "Fill in the details below": "Fill in the details below",
          "The field is empty": "The field is empty",
          "No users found": "No users found",
          "Are You Sure?": "Are You Sure?",
          "Are you sure you want to logout?": "Are you sure you want to logout?",
          "General (All)": "General (All)",
          "All": "All",
          "Category Filter": "Category Filter",
          "Sub-Category": "Sub-Category",
          "Cat/Sub": "Cat/Sub",
          "Last Stock In": "Last Stock In",
          "Bill No": "Bill No",
          "No Stock Found": "No Stock Found",
          "No Purchases Found": "No Purchases Found",
          "Financial Overview": "Financial Overview",
          "Revenue": "Revenue",
          "Current Balance": "Current Balance",
          "Viewing/Printing Purchase Invoice feature coming soon...": "Viewing/Printing Purchase Invoice feature coming soon...",
          "Professional Invoice": "Professional Invoice",
          "Other Info": "Other Info",
          "Save Profile": "Save Profile",
          "Save This Bill To A Supplier Account": "Save This Bill To A Supplier Account",
          "Search Product Name or SN...": "Search Product Name or SN...",
          "Scan or search to add items": "Scan or search to add items",
          "PAYMENT": "PAYMENT",
          "TOTAL AMOUNT": "TOTAL AMOUNT",
          "Checkout": "Checkout",
          "Edit Item": "Edit Item",
          "Payment Bill": "Payment Bill",
          "Payed": "Payed",
          "Change": "Change",
          "Search Result": "Search Result",
          "Purchase saved!": "Purchase saved!",
          "From": "From",
          "To": "To",
          "Store Movement": "Store Movement",
          "Best Selling Chart": "Best Selling Chart",
          "Least Selling Chart": "Least Selling Chart",
          "Low Stock Products": "Low Stock Products",
        },
        "hi": {
          "HOME": "होम",
          "Purchases": "खरीदारी",
          "Make Sale": "बिक्री करें",
          "Vendor Master": "वेंडर मास्टर",
          "Stock Report": "स्टॉक रिपोर्ट",
          "Accounts": "खाते",
          "Performance": "प्रदर्शन",
          "Generate Offers": "ऑफर जनरेट करें",
          "Reset Maneger Password": "मैनेजर पासवर्ड रीसेट करें",
          "Reset Password": "पासवर्ड रीसेट करें",
          "Logout": "लॉग आउट",
          "Cancel": "रद्द करें",
          "Yes": "हाँ",
          "Product Name": "उत्पाद का नाम",
          "Cost": "लागत",
          "Price": "कीमत",
          "Quantity": "मात्रा",
          "Available Quantity": "उपलब्ध मात्रा",
          "Total": "कुल",
          "TOTAL": "कुल",
          "Sold Quantity": "बेची गई मात्रा",
          "Search Product Name Or SN": "उत्पाद का नाम या SN खोजें",
          "Choose Bill Date": "बिल की तारीख चुनें",
          "Make A Sale": "बिक्री करें",
          "Buy from a Supplier": "आपूर्तिकर्ता से खरीदें",
          "Payment": "भुगतान",
          "BUY": "खरीदें",
          "Cashier Screens": "कैशियर स्क्रीन",
          "Add New Supplier": "नया आपूर्तिकर्ता जोड़ें",
          "Supplier Name": "आपूर्तिकर्ता का नाम",
          "Save": "सहेजें",
          "Phone number": "फोन नंबर",
          "Suppliers List": "आपूर्तिकर्ताओं की सूची",
          "Category": "श्रेणी",
          "Products List": "उत्पादों की सूची",
          "Delete": "हटाएं",
          "Edit": "संपादित करें",
          "Login": "लॉग इन",
          "Name": "नाम",
          "Email": "ईमेल",
          "Sign Up": "साइन अप करें",
          "Password": "पासवर्ड",
          "The e-mail not valid": "ई-मेल मान्य नहीं है",
          "The field is empty": "क्षेत्र खाली है",
          "Don't Have An Account?": "क्या आपके पास खाता नहीं है?",
          "Already Have A Account?": "क्या आपके पास पहले से खाता है?",
          "Maneger Password": "मैनेजर पासवर्ड",
          "Maneger": "मैनेजर",
          "Employees": "कर्मचारी",
          "Changing": "बदल रहा है",
          "The password is less than 8 char": "पासवर्ड 8 अक्षरों से कम है",
          "Sales": "बिक्री",
          "Seles Reports": "बिक्री रिपोर्ट",
          "New Password": "नया पासवर्ड",
          "Current Password": "वर्तमान पासवर्ड",
          "Product Information": "उत्पाद की जानकारी",
          "New Quantity": "नई मात्रा",
          "Old cost": "पुरानी लागत",
          "New cost": "नई लागत",
          "Done": "पूरा हुआ",
          "Success process": "सफल प्रक्रिया",
          "Alert!": "चेतावनी!",
          "Change Language": "भाषा बदलें",
          "Stock In QTY": "स्टॉक इन मात्रा",
          "Rate per QTY": "प्रति मात्रा दर",
          "Total Value": "कुल मूल्य",
          "Category Master": "कैटेगरी मास्टर",
          "Sub Category Master": "सब कैटेगरी मास्टर",
          "Item Master": "आइटम मास्टर",
          "Brand Master": "ब्रांड मास्टर",
          "Company Profile": "कंपनी प्रोफाइल",
          "Business Details": "व्यवसाय विवरण",
          "Business Name": "व्यवसाय का नाम",
          "Contact Details": "संपर्क विवरण",
          "Contact Person Name": "संपर्क व्यक्ति का नाम",
          "Contact Number": "संपर्क नंबर",
          "Email ID": "ईमेल आईडी",
          "Business Number": "व्यावसायिक नंबर",
          "PAN": "पैन",
          "GST": "जीएसटी",
          "Registration Number": "पंजीकरण संख्या",
          "Licence Number": "लाइसेंस संख्या",
          "Business Description": "व्यवसाय विवरण",
          "Social Media": "सोशल मीडिया",
          "Website": "वेबसाइट",
          "LinkedIn": "लिंक्डइन",
          "Instagram": "इंस्टाग्राम",
          "Facebook": "फेसबुक",
          "X": "एक्स",
          "Miscellaneous Info": "विविध जानकारी",
          "Active": "सक्रिय",
          "Inactive": "निष्क्रिय",
          "Order Type": "ऑर्डर का प्रकार",
          "Item wise": "आइटम वार",
          "Combo": "कॉम्बो",
          "Discount": "छूट",
          "Net Payable Amount": "शुद्ध देय राशि",
          "Make Purchase": "खरीद करें",
          "Vendor": "विक्रेता",
          "Purchase Reports": "खरीद रिपोर्ट",
          "Masters Setup": "मास्टर्स सेटअप",
          "Address": "पता",
          "City": "शहर",
          "Pin Code": "पिन कोड",
          "State": "राज्य",
          "Country": "देश",
          "Logo": "लोगो",
          "Profile Photo": "प्रोफ़ाइल फोटो",
          "Success": "सफलता",
          "Company profile saved!": "कंपनी प्रोफाइल सहेजी गई!",
          "Tap to upload logo": "लोगो अपलोड करने के लिए टैप करें",
          "Logo Uploaded": "लोगो अपलोड किया गया",
          "Profile Photo Uploaded": "प्रोफ़ाइल फोटो अपलोड की गई",
          "Welcome Back": "वापसी पर स्वागत है",
          "Sign in to your store account": "अपने स्टोर खाते में साइन इन करें",
          "Create Account": "खाता बनाएं",
          "Set up your store account": "अपना स्टोर खाता सेटअप करें",
          "Continue with Google": "गूगल के साथ जारी रखें",
          "Select Language": "भाषा चुनें",
          "Full Name": "पूरा नाम",
          "The field is empty": "क्षेत्र खाली है",
          "Password must be at least 8 characters": "पासवर्ड कम से कम 8 अक्षरों का होना चाहिए",
          "Sign In Failed": "साइन इन विफल रहा",
          "OR": "या",
          "Already have an account?": "क्या आपके पास पहले से खाता है?",
          "Required": "आवश्यक",
          "Category Name": "श्रेणी का नाम",
          "Sub Category Name": "उप श्रेणी का नाम",
          "Brand Name": "ब्रांड का नाम",
          "Item Name": "आइटम का नाम",
          "Status": "स्थिति",
          "Sub Categories": "उप श्रेणियां",
          "Category Details": "श्रेणी विवरण",
          "Sub Category Details": "उप श्रेणी विवरण",
          "Brand Details": "ब्रांड विवरण",
          "Item Details": "आइटम विवरण",
          "Back": "पीछे",
          "Add Category": "श्रेणी जोड़ें",
          "Edit Category": "श्रेणी संपादित करें",
          "Add Sub Category": "उप श्रेणी जोड़ें",
          "Edit Sub Category": "उप श्रेणी संपादित करें",
          "Add Brand": "ब्रांड जोड़ें",
          "Edit Brand": "ब्रांड संपादित करें",
          "Add Item": "आइटम जोड़ें",
          "Edit Item": "आइटम संपादित करें",
          "Combo Price": "कॉम्बो कीमत",
          "Items in Combo": "कॉम्बो में आइटम",
          "QTY": "मात्रा",
          "Add Combo": "कॉम्बो जोड़ें",
          "Edit Combo": "कॉम्बो संपादित करें",
          "No combos yet. Tap + to add.": "अभी तक कोई कॉम्बो नहीं। जोड़ने के लिए + पर टैप करें।",
          "Add at least one item": "कम से कम एक आइटम जोड़ें",
          "No vendors yet. Tap + to add.": "अभी तक कोई विक्रेता नहीं। जोड़ने के लिए + पर टैप करें।",
          "Add Vendor": "विक्रेता जोड़ें",
          "Edit Vendor": "विक्रेता संपादित करें",
          "Seles Reports": "बिक्री रिपोर्ट",
          "Add User": "उपयोगकर्ता जोड़ें",
          "Add New User": "नया उपयोगकर्ता जोड़ें",
          "Fill in the details below": "नीचे विवरण भरें",
          "The field is empty": "क्षेत्र खाली है",
          "No users found": "कोई उपयोगकर्ता नहीं मिला",
          "Are You Sure?": "क्या आपको यकीन है?",
          "Are you sure you want to logout?": "क्या आप वाकई लॉग आउट करना चाहते हैं?",
          "General (All)": "सामान्य (सभी)",
          "All": "सभी",
          "Category Filter": "श्रेणी फ़िल्टर",
          "Sub-Category": "उप-श्रेणी",
          "Cat/Sub": "श्रेणी/उप-श्रेणी",
          "Last Stock In": "अंतिम स्टॉक इन",
          "Bill No": "बिल नंबर",
          "No Stock Found": "कोई स्टॉक नहीं मिला",
          "No Purchases Found": "कोई खरीदारी नहीं मिली",
          "Financial Overview": "वित्तीय अवलोकन",
          "Revenue": "राजस्व",
          "Current Balance": "वर्तमान शेष",
          "Viewing/Printing Purchase Invoice feature coming soon...": "खरीद चालान देखने/प्रिंट करने की सुविधा जल्द आ रही है...",
          "Professional Invoice": "पेशेवर चालान",
          "Other Info": "अन्य जानकारी",
          "Save Profile": "प्रोफ़ाइल सहेजें",
          "Save This Bill To A Supplier Account": "इस बिल को आपूर्तिकर्ता खाते में सहेजें",
          "Search Product Name or SN...": "उत्पाद का नाम या SN खोजें...",
          "Scan or search to add items": "आइटम जोड़ने के लिए स्कैन या खोजें",
          "PAYMENT": "भुगतान",
          "TOTAL AMOUNT": "कुल राशि",
          "Checkout": "चेकआउट",
          "Edit Item": "आइटम संपादित करें",
          "Payment Bill": "भुगतान बिल",
          "Payed": "भुगतान किया",
          "Change": "बदलाव (छुट्टे)",
          "Search Result": "खोज परिणाम",
          "Purchase saved!": "खरीदारी सफल रही!",
          "From": "से",
          "To": "तक",
          "Store Movement": "स्टॉक गतिविधि",
          "Best Selling Chart": "बेस्ट सेलिंग चार्ट",
          "Least Selling Chart": "सबसे कम बिक्री चार्ट",
          "Low Stock Products": "कम स्टॉक वाले उत्पाद",
        },
        "gu": {
          "HOME": "હોમ",
          "Purchases": "ખરીદી",
          "Make Sale": "વેચાણ કરો",
          "Vendor Master": "વેન્ડર માસ્ટર",
          "Stock Report": "સ્ટોક રિપોર્ટ",
          "Accounts": "એકાઉન્ટ્સ",
          "Performance": "કામગીરી",
          "Generate Offers": "ઑફર્સ જનરેટ કરો",
          "Reset Maneger Password": "મેનેજર પાસવર્ડ ફરીથી સેટ કરો",
          "Reset Password": "પાસવર્ડ ફરીથી સેટ કરો",
          "Logout": "લૉગ આઉટ",
          "Cancel": "રદ કરો",
          "Yes": "હા",
          "Product Name": "ઉત્પાદન નામ",
          "Cost": "કિંમત",
          "Price": "ભાવ",
          "Quantity": "જથ્થો",
          "Available Quantity": "ઉપલબ્ધ જથ્થો",
          "Total": "કુલ",
          "TOTAL": "કુલ",
          "Sold Quantity": "વેચાયેલ જથ્થો",
          "Search Product Name Or SN": "ઉત્પાદન નામ અથવા SN શોધો",
          "Choose Bill Date": "બિલની તારીખ પસંદ કરો",
          "Make A Sale": "વેચાણ કરો",
          "Buy from a Supplier": "સપ્લાયર પાસેથી ખરીદો",
          "Payment": "ચુકવણી",
          "BUY": "ખરીદો",
          "Cashier Screens": "કેશિયર સ્ક્રીન",
          "Add New Supplier": "નવો સપ્લાયર ઉમેરો",
          "Supplier Name": "સપ્લાયરનું નામ",
          "Save": "સાચવો",
          "Phone number": "ફોન નંબર",
          "Suppliers List": "સપ્લાયરોની સૂચિ",
          "Category": "શ્રેણી",
          "Products List": "ઉત્પાદનોની સૂચિ",
          "Delete": "કાઢી નાખો",
          "Edit": "સંપાદિત કરો",
          "Login": "લૉગિન",
          "Name": "નામ",
          "Email": "ઈમેલ",
          "Sign Up": "સાઇન અપ કરો",
          "Password": "પાસવર્ડ",
          "The e-mail not valid": "ઈ-મેલ માન્ય નથી",
          "The field is empty": "ક્ષેત્ર ખાલી છે",
          "Don't Have An Account?": "શું તમારી પાસે એકાઉન્ટ નથી?",
          "Already Have A Account?": "શું તમારી પાસે પહેલેથી જ એકાઉન્ટ છે?",
          "Maneger Password": "મેનેજર પાસવર્ડ",
          "Maneger": "મેનેજર",
          "Employees": "કર્મચારીઓ",
          "Changing": "બદલાઈ રહ્યું છે",
          "The password is less than 8 char": "પાસવર્ડ 8 અક્ષરોથી ઓછો છે",
          "Sales": "વેચાણ",
          "Seles Reports": "વેચાણ અહેવાલો",
          "New Password": "નવો પાસવર્ડ",
          "Current Password": "વર્તમાન પાસવર્ડ",
          "Product Information": "ઉત્પાદન માહિતી",
          "New Quantity": "નવો જથ્થો",
          "Old cost": "જૂનો ખર્ચ",
          "New cost": "નવો ખર્ચ",
          "Done": "થઈ ગયું",
          "Success process": "સફળ પ્રક્રિયા",
          "Alert!": "ચેતવણી!",
          "Change Language": "ભાષા બદલો",
          "Stock In QTY": "સ્ટોક ઇન જથ્થો",
          "Rate per QTY": "પ્રતિ જથ્થો દર",
          "Total Value": "કુલ મૂલ્ય",
          "Category Master": "કેટેગરી માસ્ટર",
          "Sub Category Master": "સબ કેટેગરી માસ્ટર",
          "Item Master": "આઇટમ માસ્ટર",
          "Brand Master": "બ્રાન્ડ માસ્ટર",
          "Company Profile": "કંપની પ્રોફાઇલ",
          "Business Details": "વ્યવસાય વિગતો",
          "Business Name": "વ્યવસાયનું નામ",
          "Contact Details": "સંપર્ક વિગતો",
          "Contact Person Name": "સંપર્ક વ્યક્તિનું નામ",
          "Contact Number": "સંપર્ક નંબર",
          "Email ID": "ઈમેલ આઈડી",
          "Business Number": "વ્યાપાર નંબર",
          "PAN": "પાન",
          "GST": "જીએસટી",
          "Registration Number": "નોંધણી નંબર",
          "Licence Number": "લાઇસન્સ નંબર",
          "Business Description": "વ્યાપાર વર્ણન",
          "Social Media": "સોશિયલ મીડિયા",
          "Website": "વેબસાઇટ",
          "LinkedIn": "લિંક્ડઇન",
          "Instagram": "ઇન્સ્ટાગ્રામ",
          "Facebook": "ફેસબુક",
          "X": "એક્સ",
          "Miscellaneous Info": "વિવિધ માહિતી",
          "Active": "સક્રિય",
          "Inactive": "નિષ્ક્રિય",
          "Order Type": "ઓર્ડર પ્રકાર",
          "Item wise": "આઇટમ મુજબ",
          "Combo": "કોમ્બો",
          "Discount": "ડિસ્કાઉન્ટ",
          "Net Payable Amount": "ચોખ્ખી ચૂકવવાપાત્ર રકમ",
          "Make Purchase": "ખરીદી કરો",
          "Vendor": "વિક્રેતા",
          "Purchase Reports": "ખરીદી અહેવાલો",
          "Masters Setup": "માસ્ટર્સ સેટઅપ",
          "Address": "સરનામું",
          "City": "શહેર",
          "Pin Code": "પિન કોડ",
          "State": "રાજ્ય",
          "Country": "દેશ",
          "Logo": "લોગો",
          "Profile Photo": "પ્રોફાઇલ ફોટો",
          "Success": "સફળતા",
          "Company profile saved!": "કંપની પ્રોફાઇલ સાચવવામાં આવી!",
          "Tap to upload logo": "લોગો અપલોડ કરવા માટે ટેપ કરો",
          "Logo Uploaded": "લોગો અપલોડ થયો",
          "Profile Photo Uploaded": "પ્રોફાઇલ ફોટો અપલોડ થયો",
          "Welcome Back": "સ્વાગત છે",
          "Sign in to your store account": "તમારા સ્ટોર એકાઉન્ટમાં સાઇન ઇન કરો",
          "Create Account": "એકાઉન્ટ બનાવો",
          "Set up your store account": "તમારું સ્ટોર એકાઉન્ટ સેટઅપ કરો",
          "Continue with Google": "ગૂગલ સાથે ચાલુ રાખો",
          "Select Language": "ભાષા પસંદ કરો",
          "Full Name": "પૂરું નામ",
          "The field is empty": "ક્ષેત્ર ખાલી છે",
          "Password must be at least 8 characters": "પાસવર્ડ ઓછામાં ઓછો 8 અક્ષરોનો હોવો જોઈએ",
          "Sign In Failed": "સાઇન ઇન નિષ્ફળ રહ્યું",
          "OR": "અથવા",
          "Already have an account?": "પહેલેથી જ એકાઉન્ટ છે?",
          "Required": "જરૂરી",
          "Category Name": "કેટેગરીનું નામ",
          "Sub Category Name": "પેટા કેટેગરીનું નામ",
          "Brand Name": "બ્રાન્ડનું નામ",
          "Item Name": "આઇટમનું નામ",
          "Status": "સ્થિતિ",
          "Sub Categories": "પેટા કેટેગરીઝ",
          "Category Details": "કેટેગરી વિગતો",
          "Sub Category Details": "પેટા કેટેગરી વિગતો",
          "Brand Details": "બ્રાન્ડ વિગતો",
          "Item Details": "આઇટમ વિગતો",
          "Back": "પાછા",
          "Add Category": "શ્રેણી ઉમેરો",
          "Edit Category": "શ્રેણી સંપાદિત કરો",
          "Add Sub Category": "પેટા શ્રેણી ઉમેરો",
          "Edit Sub Category": "પેટા શ્રેણી સંપાદિત કરો",
          "Add Brand": "બ્રાન્ડ ઉમેરો",
          "Edit Brand": "બ્રાન્ડ સંપાદિત કરો",
          "Add Item": "આઇટમ ઉમેરો",
          "Edit Item": "આઇટમ સંપાદિત કરો",
          "Combo Price": "કોમ્બો કિંમત",
          "Items in Combo": "કોમ્બોમાં આઇટમ્સ",
          "QTY": "જથ્થો",
          "Add Combo": "કોમ્બો ઉમેરો",
          "Edit Combo": "કોમ્બો સંપાદિત કરો",
          "No combos yet. Tap + to add.": "હજુ સુધી કોઈ કોમ્બો નથી. ઉમેરવા માટે + ટેપ કરો.",
          "Add at least one item": "ઓછામાં ઓછી એક આઇટમ ઉમેરો",
          "No vendors yet. Tap + to add.": "હજુ સુધી કોઈ વિક્રેતા નથી. ઉમેરવા માટે + ટેપ કરો.",
          "Add Vendor": "વિક્રેતા ઉમેરો",
          "Edit Vendor": "વિક્રેતા સંપાદિત કરો",
          "Seles Reports": "વેચાણ અહેવાલો",
          "Add User": "વપરાશકર્તા ઉમેરો",
          "Add New User": "નવો વપરાશકર્તા ઉમેરો",
          "Fill in the details below": "નીચેની વિગતો ભરો",
          "The field is empty": "ક્ષેત્ર ખાલી છે",
          "No users found": "કોઈ વપરાશકર્તા મળ્યા નથી",
          "Are You Sure?": "શું તમે ખરેખર કરવા માંગો છો?",
          "Are you sure you want to logout?": "શું તમે ખરેખર લોગ આઉટ કરવા માંગો છો?",
          "General (All)": "સામાન્ય (બધું)",
          "All": "બધું",
          "Category Filter": "શ્રેણી ફિલ્ટર",
          "Sub-Category": "પેટા-શ્રેણી",
          "Cat/Sub": "શ્રેણી/પેટા-શ્રેણી",
          "Last Stock In": "છેલ્લો સ્ટોક ઇન",
          "Bill No": "બિલ નંબર",
          "No Stock Found": "કોઈ સ્ટોક મળ્યો નથી",
          "No Purchases Found": "કોઈ ખરીદી મળી નથી",
          "Financial Overview": "નાણાકીય વિહંગાવલોકન",
          "Revenue": "મહેસૂલ",
          "Current Balance": "વર્તમાન સિલક",
          "Viewing/Printing Purchase Invoice feature coming soon...": "ખરીદી ઇનવોઇસ જોવાની/પ્રિન્ટ કરવાની સુવિધા ટૂંક સમયમાં આવી રહી છે...",
          "Professional Invoice": "પ્રોફેશનલ ઇનવોઇસ",
          "Other Info": "અન્ય માહિતી",
          "Save Profile": "પ્રોફાઇલ સાચવો",
          "Save This Bill To A Supplier Account": "આ બિલ સપ્લાયર ખાતામાં સાચવો",
          "Search Product Name or SN...": "ઉત્પાદન નામ અથવા SN શોધો...",
          "Scan or search to add items": "વસ્તુઓ ઉમેરવા માટે સ્કેન અથવા શોધો",
          "PAYMENT": "ચુકવણી",
          "TOTAL AMOUNT": "કુલ રકમ",
          "Checkout": "ચેકઆઉટ",
          "Edit Item": "આઇટમ સંપાદિત કરો",
          "Payment Bill": "ચુકવણી બિલ",
          "Payed": "ચૂકવવામાં આવ્યું",
          "Change": "ફેરફાર (છુટા)",
          "Search Result": "શોધ પરિણામ",
          "Purchase saved!": "ખરીદી સાચવવામાં આવી!",
          "From": "થી",
          "To": "સુધી",
          "Store Movement": "સ્ટોક હલનચલન",
          "Best Selling Chart": "બેસ્ટ સેલિંગ ચાર્ટ",
          "Least Selling Chart": "સૌથી ઓછી વેચાતી વસ્તુઓ",
          "Low Stock Products": "ઓછો સ્ટોક ધરાવતી વસ્તુઓ",
        },
      };
}
